Support special characters in username/password
tartale/go-mssqldb pull request #1
Opened 2016-09-21 21:21 UTC by tartale

* Added unit tests that exhibit usernames/passwords that currently don't work
* Added an alternate connection string parsing that uses tabs instead of ;
    * Alternate parsing does not trim username/password values

2016-09-21 21:28 UTC, oldenbur commented on mssql.go
> +			if name != "user id" && name != "password" {
factor these strings into constants?

2016-09-21 21:29 UTC, oldenbur commented
👍 one comment, good coverage

2016-09-21 21:29 UTC, oldenbur approved these changes
one comment, good coverage

2016-09-21 21:41 UTC, tartale commented on mssql.go
> +			if name != "user id" && name != "password" {
Good suggestion; done in following commit

2016-09-21 22:54 UTC, lcaballero commented on mssql.go
> +	PASSWORD_KEY = "password"
I thought the key was `User Id` without the '_'.

2016-09-21 22:56 UTC, lcaballero commented on mssql.go
> +		if len(name) == 0 {
Would this only happen for a poorly formed string?  You'd have to return an error to indicate as much, so maybe open an issue where the parseConnectionString in general doesn't handle poorly formed string (since it's also in the original)?

2016-09-21 23:04 UTC, lcaballero commented on mssql_test.go
> +	if val, ok := res["password"]; ok {
Need to test `user id` as well for these cases since it's a special case when trimming whitespace.  It likely doesn't work due to the `_` in the reference key.

2016-09-21 23:04 UTC, lcaballero requested changes
Need to update with user_id_key tests.

2016-09-22 02:19 UTC, tartale commented on mssql.go
> +	PASSWORD_KEY = "password"
whoops; I'll fix it in the next commit.  good catch

2016-09-22 02:23 UTC, tartale commented on mssql.go
> +		if len(name) == 0 {
I'm assuming that was the purpose; the value would be thrown away in this case.  I'll see if there's an issue, if not I'll create one.

2016-09-22 02:30 UTC, tartale commented on mssql_test.go
> +	if val, ok := res["password"]; ok {
Agreed; I'll add it in the next commit

2016-09-22 02:45 UTC, merged

2016-09-22 03:16 UTC, tartale commented on mssql.go
> +		if len(name) == 0 {
Added an issue:  https://github.com/denisenkom/go-mssqldb/issues/171